name: Gigaspace XAP Documentation Portal 
markdown: kramdown
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
pygments: true
latest_xap_release: "9.7"