name: Gigaspace XAP Documentation Portal
markdown: kramdown
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlight: true
encoding: UTF-8

latest_xap_release: "10.0"
latest_xap_version: "10.0.0"

# latest_maven_version: "10.0.0-11600-RELEASE"

petclinic_jpa_branch: "10_0_0_ga"

# latest_build_filename: "gigaspaces-xap-premium-10.0.0-ga-b11600.zip"
# latest_msi_filename: "GigaSpaces-XAP.NET-Premium-10.0.0.11600-GA-x86.msi"

# latest_gshome_dirname: "gigaspaces-xap-premium-10.0.0-ga"

latest_gshome_net_dirname: "XAP.NET 10.0.0 x86"

# latest_default_lookup_group: "gigaspaces-10.0.0-XAPPremium-ga"

latest_java_url: "/xap100"
latest_net_url: "/xap100net"
latest_adm_url: "/xap100adm"
latest_sec_url: "/xap100sec"


latest_cloudify_release: "2.7"

base_javadoc_url: "http://www.gigaspaces.com/docs/JavaDoc%{version}/index.html?%{fqcn}.html"
base_scaladoc_url: "http://www.gigaspaces.com/docs/scaladocs%{version}/#%{fqcn}"
base_dotnetdoc_url: "http://www.gigaspaces.com/docs/dotnetdocs%{version}/html/T_%{fqcn}.htm"

categories-list: ["SBP", "XAP97", "XAP97NET", "XAP97ADM", "XAP100", "XAP100NET", "XAP100ADM", "XAP100SEC", "PRODUCT_OVERVIEW", "API_DOCUMENTATION", "EARLY_ACCESS", "HOWTO" , "FAQ" ,"RELEASE_NOTES" ]
